# -nodeploy to commit and not run.

name: (LIVE) Create a Release

on:

  push:
    branches:
      - 'releases/**'
  workflow_dispatch:

# ┌─────────────────────────────────────┐
# │        ENVIRONMENT VARIABLES        │
# └─────────────────────────────────────┘
env:
  server: labs
  dbfile: 'labs_londonparkour_com.sql'
  ssh:    'root@londonparkour.com'
  dest:   '/var/www/vhosts/labs.londonparkour.com'     # no slash on the end
  theme:  'wp-theme__labs-londonparkour'
  devdb:  'labs_londonparkour_com'

  # ┌─────────────────────────────────────┐
  # │          SECRETS REQUIRED           │
  # └─────────────────────────────────────┘
  #
  # 1. {{secrets.DEPLOY_KEY}}
  #    ssh key for server. ~/.ssh/id_github_ci
  #
  # 2. {{secrets.MYSQL_PASSWORD}} 
  #    MySQL Password for ldnpk${{ env.server }} user.  
  #    Generate secure password using keepass for this new user.
  # 
  # 3. {{secrets.MYSQL_ROOT_PASSWORD}} 
  #    MySQL Password for root user.
  #    Stored in Keepass.

  
jobs:

  build:
    runs-on: ubuntu-latest

    # RUN IF -nodeploy is NOT in commit message
    # Allows you to commit without running the actions.
    # ---------------------------------------------------------
    if: "!contains(github.event.head_commit.message, '-nodeploy')"
    # ---------------------------------------------------------

    steps:


      # Checkout repo with submodules
      # https://github.com/marketplace/actions/checkout-sub modules 
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      
      # https://dev.to/shofol/run-your-github-actions-jobs-from-a-specific-directory-1i9e
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x  
          
            
      # Install NPM Packages
      - name: NPM Install
        run: |
          find . ! -path "*/node_modules/*"  -name "package.json"  -execdir npm install \;


      # Install SHARP (sharp.pixelplumbing.com)
      - name: Sharp.js WEBP Image Conversion
        run: |
          npm install -g sharp-cli
          cd ./wp-content/uploads
          sharp --input **/*.png --output {dir}/{name}.webp --format "webp"
          sharp --input **/*.jpg --output {dir}/{name}.webp --format "webp"



      # Install Composer Packages in wp-plugin__ and wp-theme__ folders
      - name: Composer Install
        run: |
          find . -path "*/wp-plugin*"  ! -path "*/vendor/*" ! -path "*/node_modules/*"  -name "composer.json"  -execdir composer install \;
          find . -path "./wp-content/themes/wp-theme*"  ! -path "*/vendor/*" ! -path "*/node_modules/*"  -name "composer.json"  -execdir composer install \;


      # Deploy repo to server
      - name: Sync Repo to Server
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete\
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.github/ \
            ./ ${{env.ssh}}:${{env.dest}}            


      # Install Database
      - name: Install Database
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.ssh}}
          privateKey: ${{secrets.DEPLOY_KEY}}
          command: |
            cd ${{env.dest}}
            git stash
            git-crypt unlock ~/secrets/${{ env.server }}/gpg_key
            git stash pop
            mysql -uroot -p${{secrets.MYSQL_ROOT_PASSWORD}} -e  "CREATE USER IF NOT EXISTS 'ldnpk${{ env.server }}'@'localhost' IDENTIFIED BY '${{secrets.MYSQL_PASSWORD}}';"
            mysql -uroot -p${{secrets.MYSQL_ROOT_PASSWORD}} -e  "GRANT ALL on ${{ env.server }}_londonparkour_com.* to 'ldnpk${{ env.server }}'@'localhost';"
            mysql -uroot -p${{secrets.MYSQL_ROOT_PASSWORD}} -e  "FLUSH PRIVILEGES;"
            mysql -uldnpk${{ env.server }} -p${{secrets.MYSQL_PASSWORD}} -e "DROP DATABASE IF EXISTS ${{ env.server }}_londonparkour_com"
            mysql -uldnpk${{ env.server }} -p${{secrets.MYSQL_PASSWORD}} -e "CREATE DATABASE ${{ env.server }}_londonparkour_com"
            mysql -uldnpk${{ env.server }} -p${{secrets.MYSQL_PASSWORD}} -h localhost ${{ env.server }}_londonparkour_com < ${{env.dest}}/wp-content/database/${{ env.dbfile }}
            mysql -uroot -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "UPDATE wp_posts SET guid = replace(guid, '${{ env.devdb }}','${{ env.server }}.londonparkour');" ${{ env.server }}_londonparkour_com
            mysql -uroot -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "UPDATE wp_posts SET post_content = replace(post_content, '${{ env.devdb }}', '${{ env.server }}.londonparkour');" ${{ env.server }}_londonparkour_com
            mysql -uroot -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "UPDATE wp_postmeta SET meta_value = replace(meta_value, '${{ env.devdb }}', '${{ env.server }}.londonparkour');" ${{ env.server }}_londonparkour_com
            mysql -uroot -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "UPDATE wp_options SET option_value = replace(option_value, '${{ env.devdb }}', '${{ env.server }}.londonparkour');" ${{ env.server }}_londonparkour_com     


      # Clone wordpress fresh install
      - name: Install Wordpress
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.ssh}}
          privateKey: ${{secrets.DEPLOY_KEY}}
          command: |
            cd ${{env.dest}}
            curl -O https://wordpress.org/latest.tar.gz
            tar --strip-components=1 -xzvf latest.tar.gz
            rm latest.tar.gz


      # Copy secrets into plugins
      - name: Copy Secrets
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.ssh}}
          privateKey: ${{secrets.DEPLOY_KEY}}
          command: |
            cp ${{env.dest}}/../${{env.server}}-config.php ${{env.dest}}/wp-config.php


      # Chown to www-data:www-data
      - name: Chown 
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.ssh}}
          privateKey: ${{secrets.DEPLOY_KEY}}
          command: |
            chown -Rf www-data:www-data ${{env.dest}}


      # Activate plugins
      - name: Setup Plugins
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.ssh}}
          privateKey: ${{secrets.DEPLOY_KEY}}
          command: |
            cd ${{env.dest}}
            sudo -u www-data wp plugin activate --all
            sudo -u www-data wp plugin update --all
            sudo -u www-data wp plugin delete hello akismet
            sudo -u www-data wp theme delete twentynineteen twentytwenty twentytwentyone
            sudo -u www-data wp eval 'flush_rewrite_rules();'


      # WGET all pages as static assets for postCSS to prune for tailwind
      # npm install -g postcss postcss-cli on server! 
      - name: PostCSS for tailwind
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.ssh}}
          privateKey: ${{secrets.DEPLOY_KEY}}
          command: |
            cd ${{env.dest}}/wp-content/themes/${{env.theme}}/src/assets/css/file_scans
            wget --input-file=page_scan_list --directory-prefix=files/ --adjust-extension -q --show-progress --no-check-certificate --base=https://${{env.server}}.londonparkour.com
            cd ..
            NODE_ENV=production /usr/local/bin/postcss ./tailwind.css --config postcss.config.js --output ./style.css