# -nodeploy to commit and not run.

name: (LIVE) TEST POSTCSS

on:

  workflow_dispatch:

# ┌─────────────────────────────────────┐
# │        ENVIRONMENT VARIABLES        │
# └─────────────────────────────────────┘
env:
  server: labs
  ssh:    'root@138.68.159.70'
  dest:   '/var/www/vhosts/labs.londonparkour.com'     # no slash on the end
  theme:  'wp-theme__labs-londonparkour'
  devdb:  'labs_londonparkour_com'
  dbfile: 'labs_londonparkour_com.sql'

  # ┌─────────────────────────────────────┐
  # │          SECRETS REQUIRED           │
  # └─────────────────────────────────────┘
  #
  # 1. {{secrets.DEPLOY_KEY}}
  #    ssh key for server. ~/.ssh/id_github_ci
  #
  # 2. {{secrets.MYSQL_PASSWORD}} 
  #    MySQL Password for ldnpk${{ env.server }} user.  
  #    Generate secure password using keepass for this new user.
  # 
  # 3. {{secrets.MYSQL_ROOT_PASSWORD}} 
  #    MySQL Password for root user.
  #    Stored in Keepass.

  
jobs:

  build:
    runs-on: ubuntu-latest

    # RUN IF -nodeploy is NOT in commit message
    # Allows you to commit without running the actions.
    # ---------------------------------------------------------
    if: "!contains(github.event.head_commit.message, '-nodeploy')"
    # ---------------------------------------------------------

    steps:

      # WGET all pages as static assets for postCSS to prune for tailwind
      # npm install -g postcss postcss-cli on server! 
      - name: PostCSS for tailwind
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.ssh}}
          privateKey: ${{secrets.DEPLOY_KEY}}
          command: |
            cd ${{env.dest}}/wp-content/themes/${{env.theme}}/src/assets/css/;
            NODE_ENV=production /usr/bin/postcss ./tailwind.css --config postcss.config.js --output ./style.css;